import { duration } from "@mui/material";

export const escaperooms = [
  // mock data de momento
  {
    escaperoomname: "theClickTrap",
    category: "escaperoom",
    theme_en: "media literacy",
    theme_es: "alfabetización mediática",
    theme_fi: "medialukutaito",
    theme_sr: "medijska pismenost",
    title_en: "The Click Trap",
    title_es: "The Click Trap",
    title_fi: "The Click Trap",
    title_sr: "The Click Trap",
    duration_en: "1 hour",  
    duration_es: "1 hora",
    duration_fi: "1 tunti",
    duration_sr: "1 sat",                 
    level_en: "easy",                 
    level_es: "fácil",    
    level_fi: "helppo",      
    level_sr: "lako",
    moreInfo_en: "more info",         
    moreInfo_es: "más info",
    moreInfo_fi: "lisätietoja",
    moreInfo_sr: "više informacija",
    longdescription_en: "At ConnectNow, a well-known influencer agency and content producer, rumours are beginning to circulate about suspicious activities: secret meetings, restricted areas and unethical agreements. Your friend Lena, an independent influencer who works with them, suspects that some people are promoting a supplement called GlowUp+ using misleading health and nutrition information, putting young people at risk. To help her, you infiltrate the company as a janitor to obtain evidence from within—documents, photos, and digital records—before they are deleted. The goal of the game is to uncover and expose how economic interests and irresponsible content creation fuel misinformation, encouraging critical thinking and source verification.",
    longdescription_es: "En ConnectNow, una conocida agencia de influencers y productora de contenidos, comienzan a circular rumores sobre actividades sospechosas: reuniones secretas, áreas restringidas y acuerdos poco éticos. Tu amiga Lena, una influencer independiente que colabora con ellos, sospecha que algunos están promoviendo un suplemento llamado GlowUp+ mediante información engañosa sobre salud y alimentación, poniendo en riesgo a los jóvenes. Para ayudarla, te infiltras como conserje para obtener pruebas desde dentro —documentos, fotos y registros digitales— antes de que los borren. El objetivo del juego es descubrir y exponer cómo los intereses económicos y la creación irresponsable de contenido alimentan la desinformación, fomentando el pensamiento crítico y la verificación de fuentes.",
    longdescription_fi: "ConnectNow, tunnettu vaikuttajien agentuuri ja sisällöntuottaja, on alkanut kiertää huhuja epäilyttävistä toimista: salaisista kokouksista, rajoitetuista alueista ja epäeettisistä sopimuksista. Ystäväsi Lena, itsenäinen vaikuttaja, joka tekee yhteistyötä heidän kanssaan, epäilee, että jotkut mainostavat GlowUp+ -nimistä ravintolisää antamalla harhaanjohtavaa tietoa terveydestä ja ravitsemuksesta, mikä vaarantaa nuorten terveyden. Auttaaksesi häntä soluttaudut talonmieheksi keräämään todisteita sisältäpäin – asiakirjoja, valokuvia ja digitaalisia tietoja – ennen kuin ne tuhotaan. Pelin tavoitteena on paljastaa, kuinka taloudelliset intressit ja vastuuton sisällöntuotanto ruokkivat väärää tietoa, ja kannustaa kriittiseen ajatteluun ja lähteiden tarkistamiseen.",
    longdescription_sr: "U ConnectNow-u, poznatoj agenciji za influensere i produkciju sadržaja, počinju da kruže glasine o sumnjivim aktivnostima: tajnim sastancima, ograničenim zonama i neetičkim dogovorima. Tvoja prijateljica Lena, nezavisna influenserka koja sarađuje sa njima, sumnja da neki promovišu suplement pod nazivom GlowUp+ koristeći obmanjujuće informacije o zdravlju i ishrani, dovodeći mlade u rizik. Da bi joj pomogao, infiltriraš se kao domar kako bi iznutra pribavio dokaze — dokumenta, fotografije i digitalne zapise — pre nego što ih obrišu. Cilj igre je otkriti i razotkriti kako ekonomski interesi i neodgovorna produkcija sadržaja podstiču dezinformacije, negujući kritičko razmišljanje i proveru izvora.", //Placeholder
    keywords: ["escape room", "Media literacy", "misinformation"],   
    image: "/assets/images/EndgameBackground.png",
    claim_en: "Become the insider who uncovers the truth: stop misinformation.",
    claim_es: "Conviértete en el infiltrado que destapa la verdad: frena la desinformación.", 
    claim_fi: "Ryhdy sisäpiiriläiseksi, joka paljastaa totuuden: lopeta väärän tiedon levittäminen.", 
    claim_sr: "Postanite insajder koji otkriva istinu: zaustavite dezinformacije.",   
    externalLink: "https://play.unity.com/en/games/3e199a2b-03aa-44c1-9ecd-5f9a308280cc/webgl-builds",  
    internalLink: "/play/theClickTrap/index.html",
   resources:                                                      
    [
      {
        resourceName : "Teacher's Guide",
        resourceName_es : "Guía didáctica",
        resourceName_en : "Teacher's Guide",
        resourceName_sr : "Vodič za nastavnike",                     
        resourceName_fi : "Opettajan opas",                       
        additionalInfo : "Teacher's Guide for educators to facilitate the escaperoom activity",
        additionalInfo_es : "Guía didáctica para educadores para facilitar la actividad de escaperoom",
        additionalInfo_sr : "Vodič za nastavnike i edukatore kako bi se olakšala aktivnost u sobi za bekstvo",
        additionalInfo_fi : "Opettajan opas kouluttajille pakohuonetoiminnan helpottamiseksi",
        tag : "Docs",
        resourceLink_es : "https://docs.google.com/document/d/1QMLHAEaBetoKYbuLx2xALDGbi1-96IgJ/export?format=pdf",
        resourceLink_en : "https://docs.google.com/document/d/1VSxRpjjeqkFae5qvW-HxNOaAEf7FfdkI/export?format=pdf",
        resourceLink_sr : "https://docs.google.com/document/d/12qFifhuwcQNbNqBXYILswF9QO9v3rBUm/export?format=pdf",
        resourceLink_fi : "https://docs.google.com/document/d/1iyvRzLuXaPa4yJQ1ZCqmenchS8eRKSbM/export?format=pdf"
      }
    ]
  },
  {
    escaperoomname: "echo",
    category: "escaperoom",
    theme_en: "media literacy",
    theme_es: "alfabetización mediática",
    theme_fi: "medialukutaito",
    theme_sr: "medijska pismenost",
    title_en: "ECHO",
    title_es: "ECHO",
    title_fi: "ECHO",
    title_sr: "ECHO",
    duration_en: "20 minutes",  
    duration_es: "20 minutos",
    duration_fi: "20 minuuttia",
    duration_sr: "20 minuta",                 
    level_en: "easy",                 
    level_es: "fácil",    
    level_fi: "helppo",      
    level_sr: "lako",
    moreInfo_en: "more info",         
    moreInfo_es: "más info",
    moreInfo_fi: "lisätietoja",
    moreInfo_sr: "više informacija",
    longdescription_en: "There is a flood of misinformation flooding the ECHO social media network. You have to act as moderator and identify the bot accounts, the AI-generated content, and the misuses of AI.",
    longdescription_es: "Hay una inundación de desinformación que fluye por la red social ECHO. Tienes que actuar como moderador e identificar las cuentas de bots, el contenido generado por IA y los usos indebidos de la IA.",
    longdescription_fi: "ECHO-sosiaalisen median verkossa on tulva väärää tietoa. Sinun on toimittava moderaattorina ja tunnistettava bottitilit, tekoälyn tuottama sisältö ja tekoälyn väärinkäytöt.",
    longdescription_sr: "Na društvenoj mreži ECHO se širi poplava dezinformacija. Morate djelovati kao moderator i identificirati bot račune, sadržaj generiran umjetnom inteligencijom i zloupotrebe umjetne inteligencije.", //Placeholder
    keywords: ["escape room", "Media literacy", "misinformation","AI"],   
    image: "/assets/images/echo.png",
    claim_en: "Stop the flood of misinformation on ECHO: identify bots, AI content, and misuse of AI.",
    claim_es: "Detén la inundación de desinformación en ECHO: identifica bots, contenido de IA y mal uso de la IA.", 
    claim_fi: "Estä väärän tiedon tulva ECHO:ssa: tunnista botit, tekoälysisältö ja tekoälyn väärinkäyttö.",
    claim_sr: "Zaustavite poplavu dezinformacija na ECHO-u: identificirajte botove, AI sadržaj i zloupotrebu AI.",
    externalLink: "https://endgameproject.github.io/ECHO/",
    resources:                                                      
    [
      {
        resourceName : "Teacher's Guide",
        resourceName_es : "Guía didáctica",
        resourceName_en : "Teacher's Guide",
        resourceName_sr : "Vodič za nastavnike",                     
        resourceName_fi : "Opettajan opas",                       
        additionalInfo : "Teacher's Guide for educators to facilitate the escaperoom activity",
        additionalInfo_es : "Guía didáctica para educadores para facilitar la actividad de escaperoom",
        additionalInfo_sr : "Vodič za nastavnike i edukatore kako bi se olakšala aktivnost u sobi za bekstvo",
        additionalInfo_fi : "Opettajan opas kouluttajille pakohuonetoiminnan helpottamiseksi",
        tag : "Docs",
        resourceLink_es : "https://docs.google.com/document/d/1PLDH2_rYHl3B7F3zOVdGRfWVNcF7Q7yi/export?format=pdf",
        resourceLink_en : "https://docs.google.com/document/d/10tXAN9rPVgwpRZKBk67vHGyvjAvUeG-G/export?format=pdf",
        resourceLink_sr : "https://docs.google.com/document/d/1K3T1eMKjAh_T394RzMdjjwaHXyYf3g5y/export?format=pdf",
        resourceLink_fi : "https://docs.google.com/document/d/1H5o44V-bTfQyyESSkgTDPV1M7TtjNYE_/export?format=pdf"
      }
    ]
  },
];
